POST localhost:8000/documents/create
Content-Type: application/json

{
  "title": "Hallo",
  "content": "Ich hörte, hier kann man Dinge notieren!",
  "private": "false"
}
###

GET localhost:8000/documents/1
###