GET localhost:8000/
###
POST localhost:8000/user/register
Content-Type: application/json

{
  "name": "Ben",
  "password": "123"
}

###
POST localhost:8000/user/login
Content-Type: application/json

{
  "name": "Ben",
  "password": "123"
}
###
POST localhost:8000/user/logout

###
DELETE localhost:8000/user/delete
