### Preparation: login as Eleonore (should be able to get a list with public notes of various authors, but only her own private notes)
POST localhost:8000/api/user/login
Content-Type: application/json

{
  "name": "Eleonore",
  "password": "Troubadour&444"
}

### Preparation: login as Elle (should be able to get a list with public notes of various authors, but only her own private notes)
POST localhost:8000/api/user/login
Content-Type: application/json

{
  "name": "Ella",
  "password": "123"
}

###
GET localhost:8000/api/documents/list
###