### Test: get a public note by a valid id
GET localhost:8000/api/documents/get/8

### Preparation: login as Eleonore (who has access to the private note with id 9)
POST localhost:8000/api/user/login
Content-Type: application/json

{
  "name": "Eleonore",
  "password": "Troubadour&444"
}

### Preparation: logout (to confirm that logged out you have no access to your own private notes)
POST localhost:8000/api/user/logout

### Preparation: login as Ella (to confirm that as Ella you have no access to Eleonores private notes)
POST localhost:8000/api/user/login
Content-Type: application/json

{
  "name": "Eleonore",
  "password": "Troubadour&444"
}

### Test: get a private note by a valid id
GET localhost:8000/api/documents/get/9
###