version: '3.8'

services:
  db:
    build:
      context: ./postgres

    image: notes/postgres

    environment: # After successfully having started the db-container, these values can be deleted from the docker_compose file.
      - NOTES_PASSWORD=Test
      - POSTGRES_USER=Test
      - POSTGRES_PASSWORD=Test

    restart: unless-stopped

    ports:
      - "5432:5432"
    volumes:
    - notes-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  notes-db: