version: '3.8'

services:
  db:
    build:
      context: ./postgres

    image: notes/postgres

    environment:
      - NOTES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=

    restart: unless-stopped

    ports:
      - "5432:5432"
    volumes:
    - notes-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"

volumes:
  notes-db: