version: '3.8'

services:
  db:
    build:
      context: ./postgres

    image: notes/postgres

    environment: # After successfully having started the db-container, these values can be deleted from the docker_compose file.
      - NOTES_PASSWORD=$NOTES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

    restart: unless-stopped

    ports:
      - "5432:5432"
    volumes:
    - notes-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:8080"

volumes:
  notes-db: