version: '3.8'

# This is intended for development purposes, please use 'docker-compose-production.yml' for a standard deployment

# The following environment variables need to be set appropriately (in a .env file for example):

# $NOTES_USER
# $NOTES_PASSWORD
# $POSTGRES_USER
# $POSTGRES_PASSWORD
# $POSTGRES_DB

# The backend uses the environment variables "NOTES_DB_HOST" when built standalone, it is set here

services:
  db:
    build:
      context: ./postgres

    image: notes/postgres

    environment:
      - NOTES_USER=$NOTES_USER
      - NOTES_PASSWORD=$NOTES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB


    restart: unless-stopped
    # Port exposed for development
    ports:
      - "5432:5432"
    volumes:
    - notes-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:8080"

volumes:
  notes-db:
