### Preparation: login (use if not already logged in)
POST localhost:8000/api/user/login
Content-Type: application/json

{
  "name": "Beni",
  "password": "123"
}

### Test: logout
POST localhost:8000/api/user/logout