### Preparation: create user, so you can test delete
POST localhost:8000/api/user/register
Content-Type: application/json

{
  "name": "DeleteTestUser",
  "password": "Troubadour&444"
}

### Preparation: login for deleteTestUser (only needed if server shut down between a successfull register and delete message for user delete)
POST localhost:8000/api/user/login
Content-Type: application/json

{
  "name": "DeleteTestUser",
  "password": "Troubadour&444"
}

### Test: delete user
DELETE localhost:8000/api/user/delete
