name: "backend tests"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: | 
          docker-compose down --volumes
          docker rmi notes/postgres
          docker rmi postgres
          source .testenv
          env $(cat ../.testenv) docker-compose up --force-recreate -d
          cd backend 
          npm ci
          npm run build --if-present
          npm run github